
# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the workspace setup script.

W_SIMICS_EXTENSION_BUILDER:=C:\PROGRA~1\Simics\SIMICS~1.6\SIMICS~1.99\..\EXTENS~1.18
W_SIMICS_MODEL_BUILDER:=C:\PROGRA~1\Simics\SIMICS~1.6\SIMICS~1.99\..\MODELB~1.46
W_SIMICS_BASE:=C:\PROGRA~1\Simics\SIMICS~1.6\SIMICS~1.99
W_SIMICS_WORKSPACE:=$(shell "$(W_SIMICS_BASE)\bin\mini-python.bat" "$(W_SIMICS_BASE)\scripts\get_short_path_name.py" -l "$(shell cd)")

SIMICS_EXTENSION_BUILDER:=$(call S_PATH,$(W_SIMICS_EXTENSION_BUILDER))
SIMICS_MODEL_BUILDER:=$(call S_PATH,$(W_SIMICS_MODEL_BUILDER))
SIMICS_BASE:=$(call S_PATH,$(W_SIMICS_BASE))
SIMICS_WORKSPACE:=$(call S_PATH,$(W_SIMICS_WORKSPACE))

INCLUDE_PATHS = C:\PROGRA~1\Simics\SIMICS~1.6\SIMICS~1.99\src\include;C:\PROGRA~1\Simics\SIMICS~1.6\SIMICS~1.99\..\EXTENS~1.18\src\include;C:\PROGRA~1\Simics\SIMICS~1.6\SIMICS~1.99\..\MODELB~1.46\src\include
CXX_INCLUDE_PATHS = C:\PROGRA~1\Simics\SIMICS~1.6\SIMICS~1.99\..\EXTENS~1.18\win32\api;C:\PROGRA~1\Simics\SIMICS~1.6\SIMICS~1.99\..\MODELB~1.46\win32\api
DML_INCLUDE_PATHS = C:\PROGRA~1\Simics\SIMICS~1.6\SIMICS~1.99\..\EXTENS~1.18\win32\bin\dml\api;C:\PROGRA~1\Simics\SIMICS~1.6\SIMICS~1.99\..\MODELB~1.46\win32\bin\dml\api

PYTHON=$(W_SIMICS_WORKSPACE)\bin\mini-python.bat

# Put user definitions in config-user.mk
-include config-user.mk

# allow user to override HOST_TYPE
ifeq (,$(HOST_TYPE))
HOST_TYPE:=$(shell $(PYTHON) $(W_SIMICS_BASE)\scripts\host_type.py)
endif

include compiler.mk

include $(SIMICS_MODEL_BUILDER)/config/workspace/config.mk.win32

